### ISSUE TITLE
[Artifacts] Fragen Katalog

### ISSUE THREAD

**Issue by marcelherd** [marcelherd/OOT-Projekt#11]
Fragen könnt ihr über meine Webseite anlegen:

--> Wer nicht weiß wie PHPMyAdmin funktioniert: nix tun oder Fragen als CSV anlegen und anhängen

http://db.marcelherd.com/

user: millionaer
pw: auf Anfrage

**Comment by limecakeio** [comment]
Wie viele Fragen wollen wir denn insgesamt haben? Ach ja, ich hab einen Pool mit ca. 1000 Fragen von WWM auf Englisch gefunden und würde mir die daraus nehmen, also bitte jetzt das Veto einreichen falls die dann doch auf Deutsch seinen sollen.

**Comment by marcelherd** [comment]
Ich denke 100 würden locker reichen. Werden ja nur 15 ausgewählt, damit sollte man genügend Änderungen zwischen jedem Run erreichen können.

Sprache ist eigentlich egal, sollte dann wohl aber auch das Interface auf Englisch schreiben

**Comment by limecakeio** [comment]
So, ich werde eine TAB-Separated Liste als .txt Datei erstellen um die Fragen einzulesen, es gibt ja eine Methode dort Fragen in die Datenbank einzuspeisen, wäre dann ggf. am schnellsten im Gegensatz dazu jede Frage per Hand im phpMyAdmin einzutippen... ok?

**Comment by limecakeio** [comment]
100 Fragen sind in der Datenbank - 30 EASY, 30 MEDIUM, 20 HARD und 10 EXTRA_HARD

**Comment by limecakeio** [comment]
Sorry... 30 HARD, dann kommen wir auch auf die Summe ;)
