### ISSUE TITLE
[Views] MainMenuView

### ISSUE THREAD

**Issue by marcelherd** [marcelherd/OOT-Projekt#3]
MainMenuView muss programmiert werden

Sketch:
![mainmenuview](https://cloud.githubusercontent.com/assets/9662662/15807749/0171fc8a-2b66-11e6-8301-0503193f494e.jpg)

Wenn einer der Buttons gedrückt wird wird am parent JFrame setView( <playView> / <highscoreView> ) etc aufgerufen

Siehe #8 für Code Beispiel (wie man aus die Daten vom Model kommt)

**Comment by Lumean97** [comment]
Closed by
https://github.com/marcelherd/OOT-Projekt/commit/212dcf3ea32808e872f151825a1c014ac7d15bdc
