### ISSUE TITLE
[Views] HighscoreView

### ISSUE THREAD

**Issue by marcelherd** [marcelherd/OOT-Projekt#6]
HighscoreView muss programmiert werden

Sketch:

![highscoreview](https://cloud.githubusercontent.com/assets/9662662/15807773/7300261a-2b66-11e6-8765-2ece4d83c50a.jpg)

Siehe #8 für Code Beispiel (wie man aus die Daten vom Model kommt)****

**Comment by limecakeio** [comment]
Ist ja jetzt schon länger fertig und der main-menu-button funktioniert auch nachdem es erstellt wurde.
